### PR TITLE
Meta: enable snapshots

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
@miketaylr the thing I'm a little unsure about is the package.json change. I hope that works.

**Comment by annevk** [comment]
It turns out you were using Bikeshed incorrectly. I fixed the obvious mistakes, but I'm not sure if the `for` attribute I added near the end has the correct value. I'd appreciate if you could check that.

**Comment by miketaylr** [comment]
> It turns out you were using Bikeshed incorrectly.

Color me unsurprised. 😅 And thanks for the fixes! Everything LGTM.

As for package.json, I'll file a bug to remove that, either I didn't know about `bikeshed watch` at the time (likely), or it didn't exist. So there's no need for the node.js `onchange` dependency.

**Comment by annevk** [comment]
As a heads up, you probably want to do commits through PRs now if you weren't already, to avoid breaking master.

**Comment by miketaylr** [comment]
👍

**Comment by miketaylr** [comment]
Oh, whoops: `The command "eval git clone --depth=50 --branch=annevk/snapshots https://github.com/whatwg/compat.git whatwg/compat" failed 3 times.`. Deleted the branch too quickly, let me restore and rekick that travis job.

**Comment by miketaylr** [comment]
https://travis-ci.org/whatwg/compat/builds/191579793 is green.

**Pull request merged**
