### PR TITLE
meta: Add June 2022 UA meeting minutes

### PR DESCRIPTION
**Pull request by miketaylr**
r? @cpeterso

### CODE REVIEW

**Comment by cpeterso** [comment]
@miketaylr - LGTM. I don't have merge permissions, so you'll have to merge your own PR.

**Comment by annevk** [comment]
Note that https://github.com/whatwg/meta/blob/main/COMMITTING.md#title-prefixes are case-sensitive. This resulted in a tweet and might also contribute to another Review Draft publication.

**Comment by miketaylr** [comment]
@annevk thx - is there any way to make it case insensitive? I'll try to remember to use "Meta" in the future, but that's maybe pretty easy to fix?

**Comment by annevk** [comment]
You'd have to change https://github.com/whatwg/participate.whatwg.org as well as the whatwg/meta documentation and `review.py` script. I'd prefer we all learn the conventions however.

Adding @domenic as I'm not really working.

**Comment by miketaylr** [comment]
Thanks @karlcow for documenting https://github.com/whatwg/meta/pull/250. I'll open a new issue to discuss case-sensitivity.

**Comment by miketaylr** [comment]
(I should also say thanks for the pointers @annevk - enjoy your time off :))

**Pull request merged**
