### PR TITLE
Meta: Markup fix in README.md

### PR DESCRIPTION
**Pull request by xfq**
Currently, the linefeed is not rendered as a newline on GitHub.

I'm also OK with changing it to an ordered list in Markdown syntax if it's preferred (although it won't be 0-indexed any more).

### CODE REVIEW

**Comment by xfq** [comment]
BTW, I'm not sure why Node.js is needed in this case. Bikeshed has a [watch](https://tabatkins.github.io/bikeshed/#cli-watch) feature.

**Comment by miketaylr** [comment]
Thanks!

> BTW, I'm not sure why Node.js is needed in this case. Bikeshed has a watch feature.

Yeah, it's not. I was using that before I discovered Bikeshed's watch -- just haven't gotten around to removing that from the README yet. :)

**Comment by xfq** [comment]
@miketaylr May I submit another PR to remove the `package.json` file and the watch part in `README.md` (or replace that part with a reference to Bikeshed's documentation)? Perhaps also remove `node_modules` in `.gitignore`.

**Comment by miketaylr** [comment]
> May I submit another PR to remove the package.json file and the watch part in README.md (or replace that part with a reference to Bikeshed's documentation)? Perhaps also remove node_modules in .gitignore.

@xfq Sounds good!

**Pull request merged**
