### PR TITLE
Review Draft Publication: June 2018

### PR DESCRIPTION
**Pull request by annevk**
A Review Draft for this Workstream will be published shortly, by merging this pull request.

Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.

### CODE REVIEW

**Comment by annevk** [comment]
@miketaylr see https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#review-drafts for details. I'll manage this round and hopefully we can get it automated next time around.

**Comment by miketaylr** [comment]
> @miketaylr see https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#review-drafts for details. I'll manage this round and hopefully we can get it automated next time around.

thanks, appreciated.

**Comment by annevk** [comment]
Updated the commit to match today's date.

**Comment by annevk** [comment]
Now live at https://compat.spec.whatwg.org/review-drafts/2018-06/.

**Pull request merged**
