### PR TITLE
-webkit-border-top-left-radius incorrectly mapped to top-RIGHT unprefixed property

### PR DESCRIPTION
**Pull request by teoli2003**
This fix it by mapping it to border-top-left-radius (as implemented in Firefox)

### CODE REVIEW

**Comment by miketaylr** [comment]
oops! thanks for the patch!

@teoli2003 could you make the change in the `compatibility.bs` instead of the html one (that's generated from the bikeshed file)? If it's too much trouble, I can do it for you.

**Comment by teoli2003** [comment]
Sure! I will.

On 08/07/2016 15:41, Mike Taylor wrote:
>
> oops! thanks for the patch!
>
> @teoli2003 <https://github.com/teoli2003> could you make the change in 
> the |compatibility.bs| instead of the html one (that's generated from 
> the bikeshed file)? If it's too much trouble, I can do it for you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/whatwg/compat/pull/57#issuecomment-231377866>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/ABZftbWoNXMuQ7AnnxquivYJe7xlx1T3ks5qTmGpgaJpZM4JIBi0>.
>


-- 
"Prenez soin des minutes, les heures prendront soin d'elles-mêmes."
P.D. Stanhope (4e baron de Chesterfield, 1694-1773)

**Comment by teoli2003** [comment]
Opened PR #58 for the change in .bs

**Comment by miketaylr** [comment]
👍

**Pull request closed without merging**
