### PR TITLE
Meta: deploy using the shared deploy script and EXTRA_FILES

### PR DESCRIPTION
**Pull request by foolip**
Depends on https://github.com/whatwg/whatwg.org/pull/68.

The generic deploy.sh already runs the HTML checker, so those bits can be removed from .travis.yml too.

### CODE REVIEW

**Comment by foolip** [comment]
This is now ready for review. It'll probably need some fixes after merging, so I'll check to see if it's working.

**Comment by foolip** [comment]
Actually, perhaps best discuss alternatives in https://github.com/whatwg/meta/issues/11#issuecomment-325594100 first.

**Comment by foolip** [comment]
The Travis status checks in this very PR have confirmed that this is working at least a little:
https://compat.spec.whatwg.org/branch-snapshots/use-common-deploy/
https://compat.spec.whatwg.org/branch-snapshots/use-common-deploy/stroked-text.png

As @domenic suggested, we can just keep the EXTRA_FILES mechanism alongside something fancier, as it'll suffice for many cases.

**Comment by annevk** [comment]
In principle this looks fine, but it fails Travis.

**Comment by foolip** [comment]
Looks like I force pushed over the HTML checker changes I made yesterday. I've restored those now, and with the other changes here and in deploy.sh, Travis is now happy.

**Pull request merged**
