### PR TITLE
Define `-webkit-transform-3d` with `Type: discrete`

### LINKED ISSUE #221: Define `-webkit-transform-3d` with `Type`
According to Media Queries:

- [*every media feature defines its “type” as either “range” or “discrete” in its definition table*](https://drafts.csswg.org/mediaqueries-5/#mq-ranges)
- [*“Discrete” type properties do not accept “min-” or “max-” prefixes*](https://drafts.csswg.org/mediaqueries-5/#mq-min-max)

Therefore I propose to replace [`Accepts min/max prefixes: no`](https://github.com/whatwg/compat/blob/c61bfe4be8e8cbcd1bfe1f52021d778a18429e50/compatibility.bs#L176) by `Type: discrete`, similarly as for [`-webkit-device-pixel-ratio`](https://compat.spec.whatwg.org/#css-media-queries-webkit-device-pixel-ratio) or other media feature names in Media Queries.

### PR DESCRIPTION
**Pull request by cdoublev**
Fixes #221.

***
<a href="https://whatpr.org/compat/222.html" title="Last updated on Nov 10, 2022, 3:26 AM UTC (0c5d5b5)">Preview</a> | <a href="https://whatpr.org/compat/222/c61bfe4...0c5d5b5.html" title="Last updated on Nov 10, 2022, 3:26 AM UTC (0c5d5b5)">Diff</a>

### CODE REVIEW

**Review by karlcow — APPROVED** [review]
Thanks a lot.

**Comment by karlcow** [comment]
@cdoublev could you go through https://participate.whatwg.org/agreement-status?user=cdoublev&repo=compat&pull=222

**Comment by cdoublev** [comment]
Damn, I did not read the *Synchronizing with GitHub* section, sorry.

**Comment by cdoublev** [comment]
Is there still something expected from me?

**Comment by karlcow** [comment]
@cdoublev yes. 
Capture d’écran 2022-11-26 à 07 29 57

**Comment by karlcow** [comment]
@annevk is there anything more than @cdoublev should do?

**Comment by karlcow** [comment]
I wonder if it's a question of public affiliation in the profile?

**Comment by cdoublev** [comment]
> `@cdoublev` has signed up to participate as an individual, but has not yet been verified. Hold tight while we sort this out on our end!

Feel free to merge your own commit! =)

**Comment by annevk** [comment]
Thanks @cdoublev!

(New contributors have to be manually verified through https://github.com/whatwg/participant-data which is why it can take a little longer. Especially when I'm not pinged. 😊 Should be smooth sailing next time around though.)

**Pull request merged**
